### PR TITLE
Fix s1s2 crashes

### PR DESCRIPTION
**Pull request by cschmidli**
this one should default the temperate score values in case `ghg_s1s2` or `ghg_s3` is missing.

pls have a look at the code and check whether it makes sense

### CODE REVIEW

**Comment by mountainrambler** [comment]
I ran some tests (in Jupyter Notebook) that showed that the proposed solution stops the program from crashing. However, the S1S2S3 score for the companies without ghg data came out as NaN, vs the expected fallback value. Will investigate further if this could be due to other factors.

**Comment by cschmidli** [comment]
hmm, if I run the test locally it seems to work fine. Which notebook are you running?

**Comment by mountainrambler** [comment]
I ran "1_analysis_example.ipynb". I'll try some of the others as well.

**Comment by mountainrambler** [comment]
I can successfully print a correct calculation when running the code inside VS Code. So there seems to be an issue with my Jupyter sessions. So the propsed fix is ok by me.

**Comment by mountainrambler** [comment]
The call to _check_column is also done later in the program when aggregating to portfolio level when using any other method than WATS. Therefore I propose that we update the documentation to explain the need for ghg data for all companies + that the error message also states that ghg data is needed for most aggregation methods.

**Comment by cschmidli** [comment]
great! let's merge it then and make a new version (1.0.1)

**Review by mountainrambler — APPROVED** [review]
So how do we bump the version number?

**Pull request merged**
